name: Publish Python Package to PyPI

on:
    release:
        types: [published]

jobs:
    build-and-publish:
        name: Build and publish Python distributions to PyPI
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write # Important for trusted publishing

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install build dependencies
              run: python -m pip install build

            - name: Build a binary wheel and a source tarball
              run: python -m build

            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              # No password needed, it uses the OIDC identity token

            - name: Create merge-back PR to dev
              continue-on-error: true
              run: |
                  owner=$(echo ${{ github.repository }} | cut -d '/' -f1)
                  repo=$(echo ${{ github.repository }} | cut -d '/' -f2)
                  tag=${{ github.ref_name }}
                  branch=$(echo $tag | sed 's/^v/release\//')
                  curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/$owner/$repo/pulls \
                    -d "{\"title\":\"Merge back $branch to dev\",\"body\":\"Automatic merge-back after release $tag\",\"head\":\"$branch\",\"base\":\"dev\"}"
